### ISSUE TITLE
Missing __version__ in generated python module 

### ISSUE THREAD

**Issue by MuellerSeb** [GeoStat-Framework/GSTools-Core#16] opened 2021-11-18 08:51 UTC
I noticed, that maturin doesn't add a `__version__` string to the generated module.

One possibility is given here: https://github.com/PyO3/maturin/issues/100#issuecomment-475325456
```rust
    m.add("__version__", env!("CARGO_PKG_VERSION"))?;
```

See also here: https://github.com/PyO3/pyo3-built/

**Comment by MuellerSeb** [comment] 2021-11-23 11:48
Also https://github.com/PyO3/pyo3-built/ would be a good thing to include, I guess.
What do you think, @LSchueler @adamreichold ?

**Comment by adamreichold** [comment] 2021-11-23 17:42
I am admittedly somewhat sceptical. Having inline provenance data is certainly nice, but do we have a specific use case in mind? Adding a build script does have a cost w.r.t. build duration and additional failure modes. (But then our build configuration uses LTO and a single codegen unit, so build times already are horrible.)

Personally, I would start with the minimal version info as suggested in the top comment.

**Comment by MuellerSeb** [comment] 2021-11-23 20:45
Ok. Then  I would suggest adding version info and making a release so we can release gstools 1.3.4

**Comment by LSchueler** [comment] 2021-11-24 17:27
Hmm, that's a tough one. Reproducibility is maybe even more important in scientific software than in other software and detailed environment info about versions, backend, ... definitely helps in that regard. But even longer build times do sound horrible.
So yeah, maybe start out with only adding the version info and afterwards we could experiment with the `pyo3-built`.

**Comment by LSchueler** [comment] 2021-11-30 18:44
I'm closing this for now due to PR #17.

**Closed by LSchueler** 2021-11-30 18:44 UTC
